name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker/build-push-action@v3
      with:
        context: ./00-spring-petclinic-deployment/spring-petclinic-rest
        file: ./00-spring-petclinic-deployment/spring-petclinic-rest/Dockerfile
        push: true
        tags: |
            spring-petclinic-rest:${{ github.sha }}
            spring-petclinic-rest:latest
